export const ALL_ROOMS_SUCCESS = 'ALL_ROOM_SUCCESS';
export const ALL_ROOMS_FAIL = 'ALL_ROOM_FAIL';
export const ALL_ROOM_DETAIL_SUCCESS = 'ALL_ROOM_DETAIL_SUCCESS';
export const ALL_ROOM_DETAIL_FAIL = 'ALL_ROOM_DETAIL_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
